version: '3.4'

services:

  axiomatika-test:
    image: postgres:11
    container_name: axiomatika-test
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
